# Generated by Django 2.1.7 on 2020-11-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_medicine', models.CharField(max_length=50)),
                ('resume', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('type_of_pet', models.CharField(max_length=50)),
                ('type_of_medicine', models.CharField(max_length=50)),
                ('amount_dose', models.CharField(max_length=50)),
                ('medicine_cost', models.IntegerField(default=0)),
            ],
        ),
    ]
